server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: resqueue_user
          uri: lb://RESQUEUE-USER
          predicates:
            - Path=/auth/**, /users/**

        - id: resqueue_clinic
          uri: lb://RESQUEUE-CLINIC
          predicates:
            - Path=/clinic/**

        - id: resqueue_vaccine
          uri: lb://RESQUEUE-VACCINE
          predicates:
            - Path=/vaccine/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_BASE_ISSUER_URL:http://localhost:9000}/realms/resqueue

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
