server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: resqueue_clinic
          uri: lb://RESQUEUE-CLINIC
          predicates:
            - Path=/hello/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.imaginer.com.br/realms/resqueue

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: https://eureka.imaginer.com.br/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
